/**
 * Style Dictionary config — generates constants/*.ts from tokens/tokens.json
 *
 * Handles Figma Tokens Studio multi-set format with cross-set reference
 * resolution. Includes hardcoded fallbacks for React Native-specific values
 * (font variant names, semantic typography compositions) that Tokens Studio
 * does not manage.
 */
import { readFileSync } from 'fs';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function loadResolvedTokens() {
  const raw = JSON.parse(readFileSync('tokens/tokens.json', 'utf8'));
  const setOrder = raw.$metadata?.tokenSetOrder || [];

  const flat = {};
  for (const setName of setOrder) {
    const setData = raw[setName];
    if (!setData) continue;
    flattenSet(setData, '', flat);
  }

  for (const key of Object.keys(flat)) {
    flat[key] = resolve(flat[key], flat);
  }

  return { raw, flat, setOrder };
}

function flattenSet(obj, prefix, flat) {
  for (const [key, val] of Object.entries(obj)) {
    if (key.startsWith('$')) continue;
    const path = prefix ? `${prefix}.${key}` : key;
    if (val && typeof val === 'object' && 'value' in val) {
      flat[path] = val.value;
    } else if (val && typeof val === 'object') {
      flattenSet(val, path, flat);
    }
  }
}

function resolve(value, flat, depth = 0) {
  if (depth > 10) return value;
  if (typeof value !== 'string') return value;
  const m = value.match(/^\{(.+)\}$/);
  if (!m) return value;
  if (flat[m[1]] !== undefined) return resolve(String(flat[m[1]]), flat, depth + 1);
  return value;
}

function lit(v) {
  if (v === undefined || v === null) return "''";
  const str = String(v);
  if (/^#[0-9a-fA-F]{3,8}$/.test(str)) return `'${str.toUpperCase()}'`;
  const n = Number(str);
  if (!isNaN(n) && str !== '' && str !== 'true' && str !== 'false') return String(n);
  return `'${str}'`;
}

function kebabToCamel(s) {
  return s.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
}

function obj(entries, indent = '  ') {
  const lines = entries.map(([k, v]) => {
    const needsQuote = /^\d/.test(k) || !/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(k);
    const key = needsQuote ? `'${k}'` : k;
    return `${indent}${key}: ${v},`;
  });
  return `{\n${lines.join('\n')}\n}`;
}

const HEADER = '// Auto-generated by Style Dictionary — do not edit manually\n';

// ---------------------------------------------------------------------------
// RN-specific fallbacks (not managed by Tokens Studio)
// ---------------------------------------------------------------------------

/** React Native / Expo font variant names. */
const FONT_FAMILY = {
  displaySemiBold: 'BarlowCondensed_600SemiBold',
  displayBold: 'BarlowCondensed_700Bold',
  displayExtraBold: 'BarlowCondensed_800ExtraBold',
  bodyRegular: 'Inter_400Regular',
  bodyMedium: 'Inter_500Medium',
  bodySemiBold: 'Inter_600SemiBold',
  bodyBold: 'Inter_700Bold',
  monoRegular: 'JetBrainsMono_400Regular',
  monoMedium: 'JetBrainsMono_500Medium',
};

/** Font sizes missing from the primitive scale but used in semantic styles. */
const EXTRA_FONT_SIZES = { 30: 30, 60: 60, 72: 72 };

/**
 * Semantic typography compositions. Uses primitive lineHeight multipliers
 * and letter-spacing values (em-relative, converted to px at build time).
 */
const SEMANTIC_TYPOGRAPHY = {
  display: [
    { size: '2xl', ff: 'displayBold',     fs: 72, lh: 1.1,  ls: -0.02 },
    { size: 'xl',  ff: 'displayBold',     fs: 60, lh: 1.1,  ls: -0.02 },
    { size: 'lg',  ff: 'displayBold',     fs: 48, lh: 1.1,  ls: -0.02 },
    { size: 'md',  ff: 'displaySemiBold', fs: 36, lh: 1.25, ls: 0 },
    { size: 'sm',  ff: 'displaySemiBold', fs: 30, lh: 1.25, ls: 0 },
  ],
  body: [
    { size: 'xl', ff: 'bodyRegular', fs: 20, lh: 1.5 },
    { size: 'lg', ff: 'bodyRegular', fs: 18, lh: 1.5 },
    { size: 'md', ff: 'bodyRegular', fs: 16, lh: 1.5 },
    { size: 'sm', ff: 'bodyRegular', fs: 14, lh: 1.5 },
    { size: 'xs', ff: 'bodyRegular', fs: 12, lh: 1.5 },
  ],
  label: [
    { size: 'lg',   ff: 'bodySemiBold', fs: 18, lh: 1.25 },
    { size: 'md',   ff: 'bodySemiBold', fs: 16, lh: 1.25 },
    { size: 'sm',   ff: 'bodyMedium',   fs: 14, lh: 1.25 },
    { size: 'caps', ff: 'bodySemiBold', fs: 12, lh: 1.25, ls: 0.15, tt: 'uppercase' },
  ],
  mono: [
    { size: 'xl', ff: 'monoMedium',  fs: 20, lh: 1.1 },
    { size: 'lg', ff: 'monoMedium',  fs: 18, lh: 1.1 },
    { size: 'md', ff: 'monoRegular', fs: 16, lh: 1.1 },
    { size: 'sm', ff: 'monoRegular', fs: 14, lh: 1.1 },
  ],
};

/** Fallback color tokens for values not yet in Tokens Studio. */
const COLOR_FALLBACKS = {
  text: { inverse: '{color.neutral.950}' },
  border: {
    'border-default': '{color.neutral.700}',
    'border-subtle': '{color.neutral.800}',
    'border-focus': '{color.blue.300}',
  },
};

// ---------------------------------------------------------------------------
// Format: ts/colors
// ---------------------------------------------------------------------------

function formatColors() {
  const { raw, flat, setOrder } = loadResolvedTokens();
  const primSet = raw[setOrder[0]] || {};
  const tokSet = raw[setOrder[1]] || {};

  function colorScale(colorName) {
    const group = primSet.color?.[colorName] || {};
    return Object.keys(group)
      .filter(k => !k.startsWith('$'))
      .map(k => [k, lit(flat[`color.${colorName}.${k}`])]);
  }

  function semanticColorGroup(groupPath, stripPrefix = '') {
    const parts = groupPath.split('.');
    let group = tokSet;
    for (const p of parts) group = group?.[p] || {};
    return Object.keys(group)
      .filter(k => !k.startsWith('$') && typeof group[k] === 'object' && 'value' in group[k])
      .map(k => {
        const cleanKey = stripPrefix && k.startsWith(`${stripPrefix}-`)
          ? k.slice(stripPrefix.length + 1)
          : k;
        return [kebabToCamel(cleanKey), lit(flat[`${groupPath}.${k}`])];
      });
  }

  const neutralEntries = colorScale('neutral');
  const blueEntries = colorScale('blue');
  const bgEntries = semanticColorGroup('color.background', 'bg');
  const brandEntries = semanticColorGroup('color.brand', 'brand');
  const textEntries = semanticColorGroup('color.text', 'text');
  const statusEntries = semanticColorGroup('color.status');
  let borderEntries = semanticColorGroup('color.border', 'border');

  // Apply fallbacks for missing tokens
  for (const [k, ref] of Object.entries(COLOR_FALLBACKS.text)) {
    if (!textEntries.find(([ek]) => ek === k)) {
      textEntries.push([k, lit(resolve(ref, flat))]);
    }
  }
  if (borderEntries.length === 0) {
    borderEntries = Object.entries(COLOR_FALLBACKS.border).map(([k, ref]) => {
      const cleanKey = k.startsWith('border-') ? k.slice(7) : k;
      return [kebabToCamel(cleanKey), lit(resolve(ref, flat))];
    });
  }

  // --- Component tokens (from components set) ---
  const compSet = raw[setOrder[2]] || {};
  const buttonGroup = compSet.button || {};
  const buttonVariants = [];

  for (const [variant, def] of Object.entries(buttonGroup)) {
    if (variant.startsWith('$')) continue;
    if (typeof def === 'object' && 'value' in def) {
      // top-level prop like radius — skip for buttonTokens
      continue;
    }
    const props = [];
    for (const [prop, val] of Object.entries(def)) {
      if (prop.startsWith('$') || typeof val !== 'object' || !('value' in val)) continue;
      props.push([prop, lit(resolve(String(val.value), flat))]);
    }
    if (props.length > 0) {
      const inner = props.map(([k, v]) => `      ${k}: ${v},`).join('\n');
      buttonVariants.push(`    ${variant}: {\n${inner}\n    }`);
    }
  }

  const buttonRadius = buttonGroup.radius?.value
    ? `    radius: ${lit(resolve(String(buttonGroup.radius.value), flat))},`
    : '';

  const buttonTokensBody = buttonVariants.length > 0
    ? `{\n${buttonVariants.join(',\n')},\n${buttonRadius ? `${buttonRadius}\n` : ''}  }`
    : '{}';

  return `${HEADER}
export const neutral = ${obj(neutralEntries)} as const;

export const blue = ${obj(blueEntries)} as const;

export const background = ${obj(bgEntries)} as const;

export const brand = ${obj(brandEntries)} as const;

export const text = ${obj(textEntries)} as const;

export const status = ${obj(statusEntries)} as const;

export const border = ${obj(borderEntries)} as const;

export const buttonTokens = ${buttonTokensBody} as const;

export const colors = {
  neutral,
  blue,
  background,
  brand,
  text,
  status,
  border,
  buttonTokens,
} as const;
`;
}

// ---------------------------------------------------------------------------
// Format: ts/spacing
// ---------------------------------------------------------------------------

function formatSpacing() {
  const { raw, flat, setOrder } = loadResolvedTokens();
  const tokSet = raw[setOrder[1]] || {};
  const spacingGroup = tokSet.spacing || {};

  const spaceEntries = [];
  const layoutEntries = [];

  for (const [k, v] of Object.entries(spacingGroup)) {
    if (k.startsWith('$') || typeof v !== 'object' || !('value' in v)) continue;
    const resolved = flat[`spacing.${k}`];

    if (k.startsWith('space-')) {
      const cleanKey = k.slice(6);
      spaceEntries.push([cleanKey, lit(resolved)]);
    } else {
      layoutEntries.push([kebabToCamel(k), lit(resolved)]);
    }
  }

  return `${HEADER}
export const space = ${obj(spaceEntries)} as const;

export const layout = ${obj(layoutEntries)} as const;

export const spacing = {
  space,
  layout,
} as const;
`;
}

// ---------------------------------------------------------------------------
// Format: ts/radius
// ---------------------------------------------------------------------------

function formatRadius() {
  const { raw, flat, setOrder } = loadResolvedTokens();
  const tokSet = raw[setOrder[1]] || {};
  const radiusGroup = tokSet.radius || {};

  const radiiEntries = [];
  const componentEntries = [];

  for (const [k, v] of Object.entries(radiusGroup)) {
    if (k.startsWith('$') || typeof v !== 'object' || !('value' in v)) continue;
    const resolved = flat[`radius.${k}`];

    if (k.startsWith('radius-')) {
      const cleanKey = k.slice(7);
      radiiEntries.push([cleanKey, lit(resolved)]);
    } else {
      componentEntries.push([kebabToCamel(k), lit(resolved)]);
    }
  }

  return `${HEADER}
export const radii = ${obj(radiiEntries)} as const;

export const componentRadius = ${obj(componentEntries)} as const;

export const radius = {
  radii,
  component: componentRadius,
} as const;
`;
}

// ---------------------------------------------------------------------------
// Format: ts/typography
// ---------------------------------------------------------------------------

function formatTypography() {
  const { raw, flat, setOrder } = loadResolvedTokens();
  const primSet = raw[setOrder[0]] || {};
  const tokSet = raw[setOrder[1]] || {};
  const typo = tokSet.typography || {};

  // fontFamily — from tokens or fallback
  let ffEntries;
  if (typo.fontFamily && Object.keys(typo.fontFamily).filter(k => !k.startsWith('$')).length > 0) {
    ffEntries = Object.keys(typo.fontFamily)
      .filter(k => !k.startsWith('$'))
      .map(k => [k, lit(flat[`typography.fontFamily.${k}`])]);
  } else {
    ffEntries = Object.entries(FONT_FAMILY).map(([k, v]) => [k, lit(v)]);
  }

  // fontSize — from primitives (supports both "font-size"/"size-N" and "fontSize"/"N" formats)
  const fsPrim = primSet.typography?.['font-size'] || primSet.typography?.fontSize || {};
  const fsPrimKeyPrefix = primSet.typography?.['font-size'] ? 'font-size' : 'fontSize';
  const fsMap = {};
  for (const k of Object.keys(fsPrim).filter(k => !k.startsWith('$'))) {
    const num = k.replace('size-', '');
    fsMap[num] = flat[`typography.${fsPrimKeyPrefix}.${k}`];
  }
  for (const [k, v] of Object.entries(EXTRA_FONT_SIZES)) {
    if (!(k in fsMap)) fsMap[k] = v;
  }
  const fsEntries = Object.keys(fsMap)
    .sort((a, b) => Number(a) - Number(b))
    .map(k => [k, lit(fsMap[k])]);

  // lineHeight — from primitives (supports both "line-height"/"leading-N" and "lineHeight"/"N" formats)
  const lhPrim = primSet.typography?.['line-height'] || primSet.typography?.lineHeight || {};
  const lhPrimKeyPrefix = primSet.typography?.['line-height'] ? 'line-height' : 'lineHeight';
  const lhEntries = Object.keys(lhPrim)
    .filter(k => !k.startsWith('$'))
    .map(k => [k.replace('leading-', ''), lit(flat[`typography.${lhPrimKeyPrefix}.${k}`])]);

  // letterSpacing — from primitives (supports both "letter-spacing"/"tracking-N" and "letterSpacing"/"N" formats)
  const lsPrim = primSet.typography?.['letter-spacing'] || primSet.typography?.letterSpacing || {};
  const lsPrimKeyPrefix = primSet.typography?.['letter-spacing'] ? 'letter-spacing' : 'letterSpacing';
  const lsEntries = Object.keys(lsPrim)
    .filter(k => !k.startsWith('$'))
    .map(k => [k.replace('tracking-', ''), lit(flat[`typography.${lsPrimKeyPrefix}.${k}`])]);

  /** Build semantic styles from tokens or fallback definitions. */
  function semanticStyles(category) {
    // Try tokens first
    const group = typo[category];
    if (group && Object.keys(group).filter(k => !k.startsWith('$')).length > 0) {
      return semanticStylesFromTokens(group, category);
    }
    // Fallback to hardcoded definitions
    const defs = SEMANTIC_TYPOGRAPHY[category];
    if (!defs) return '{}';
    return semanticStylesFromDefs(defs);
  }

  function semanticStylesFromTokens(group, category) {
    // Build lookup from SEMANTIC_TYPOGRAPHY for RN-specific font families + extras
    const fallbackDefs = SEMANTIC_TYPOGRAPHY[category] || [];
    const fallbackMap = {};
    for (const d of fallbackDefs) fallbackMap[d.size] = d;

    const entries = [];
    for (const [size, def] of Object.entries(group)) {
      if (size.startsWith('$')) continue;
      // fontSize + lineHeight from tokens (resolveRef unwraps token objects)
      const fs = Number(resolveRef(def.fontSize));
      const lh = Number(resolveRef(def.lineHeight));
      const computed = Math.round(fs * lh * 100) / 100;
      // fontFamily from SEMANTIC_TYPOGRAPHY (RN variant name with correct weight)
      const fb = fallbackMap[size];
      const ff = fb ? (FONT_FAMILY[fb.ff] || fb.ff) : String(resolveRef(def.fontFamily));
      const props = [`    fontFamily: '${ff}'`, `    fontSize: ${fs}`, `    lineHeight: ${computed}`];
      // letterSpacing: prefer fallback (em-relative), fall back to token value
      if (fb?.ls !== undefined) {
        const lsAbs = Math.abs(fb.ls) < 1 ? Math.round(fs * fb.ls * 100) / 100 : fb.ls;
        props.push(`    letterSpacing: ${lsAbs}`);
      } else if (def.letterSpacing) {
        const lsRaw = Number(resolveRef(def.letterSpacing));
        const lsAbs = Math.abs(lsRaw) < 1 ? Math.round(fs * lsRaw * 100) / 100 : lsRaw;
        props.push(`    letterSpacing: ${lsAbs}`);
      }
      // textTransform from fallback or token
      if (fb?.tt) {
        props.push(`    textTransform: '${fb.tt}' as const`);
      } else if (def.textTransform) {
        props.push(`    textTransform: '${def.textTransform}' as const`);
      }
      const key = /^\d/.test(size) || size.includes('xl') ? `'${size}'` : size;
      entries.push(`  ${key}: {\n${props.join(',\n')},\n  }`);
    }
    return `{\n${entries.join(',\n')},\n}`;
  }

  function semanticStylesFromDefs(defs) {
    const entries = [];
    for (const d of defs) {
      const ff = FONT_FAMILY[d.ff] || d.ff;
      const computed = Math.round(d.fs * d.lh * 100) / 100;
      const props = [`    fontFamily: '${ff}'`, `    fontSize: ${d.fs}`, `    lineHeight: ${computed}`];
      if (d.ls !== undefined) {
        const lsAbs = Math.abs(d.ls) < 1 ? Math.round(d.fs * d.ls * 100) / 100 : d.ls;
        props.push(`    letterSpacing: ${lsAbs}`);
      }
      if (d.tt) props.push(`    textTransform: '${d.tt}' as const`);
      const key = /^\d/.test(d.size) || d.size.includes('xl') ? `'${d.size}'` : d.size;
      entries.push(`  ${key}: {\n${props.join(',\n')},\n  }`);
    }
    return `{\n${entries.join(',\n')},\n}`;
  }

  function resolveRef(val) {
    // Unwrap token objects like {value: "{...}", type: "fontSizes"}
    if (val && typeof val === 'object' && 'value' in val) val = val.value;
    if (typeof val !== 'string') return val;
    const m = val.match(/^\{(.+)\}$/);
    if (m && flat[m[1]] !== undefined) return flat[m[1]];
    return val;
  }

  return `${HEADER}
export const fontFamily = ${obj(ffEntries)} as const;

export const fontSize = ${obj(fsEntries)} as const;

export const lineHeight = ${obj(lhEntries)} as const;

export const letterSpacing = ${obj(lsEntries)} as const;

export const display = ${semanticStyles('display')} as const;

export const body = ${semanticStyles('body')} as const;

export const label = ${semanticStyles('label')} as const;

export const mono = ${semanticStyles('mono')} as const;

export const typography = {
  fontFamily,
  fontSize,
  lineHeight,
  letterSpacing,
  display,
  body,
  label,
  mono,
} as const;
`;
}

// ---------------------------------------------------------------------------
// Style Dictionary config
// ---------------------------------------------------------------------------

/** @type {import('style-dictionary').Config} */
export default {
  source: ['tokens/tokens.json'],
  log: {
    verbosity: 'silent',
    errors: {
      brokenReferences: 'console',
    },
  },
  platforms: {
    ts: {
      buildPath: 'constants/',
      files: [
        { destination: 'colors.ts', format: 'ts/colors' },
        { destination: 'spacing.ts', format: 'ts/spacing' },
        { destination: 'radius.ts', format: 'ts/radius' },
        { destination: 'typography.ts', format: 'ts/typography' },
      ],
    },
  },
  hooks: {
    formats: {
      'ts/colors': () => formatColors(),
      'ts/spacing': () => formatSpacing(),
      'ts/radius': () => formatRadius(),
      'ts/typography': () => formatTypography(),
    },
  },
};
