// Auto-generated by Style Dictionary — do not edit manually

export const neutral = {
  '0': '#FFFFFF',
  '50': '#F8FAFC',
  '100': '#F1F5F9',
  '200': '#E2E8F0',
  '300': '#CBD5E1',
  '400': '#94A3B8',
  '500': '#64748B',
  '600': '#475569',
  '700': '#334155',
  '800': '#1C1C26',
  '900': '#13131A',
  '950': '#0A0A0F',
} as const;

export const blue = {
  '50': '#E0F9FF',
  '100': '#B3F0FF',
  '200': '#66E2FF',
  '300': '#00D4FF',
  '400': '#00BFEA',
  '500': '#0099CC',
  '600': '#0077A8',
  '700': '#005580',
  '800': '#003D5C',
  '900': '#001A2E',
  '950': '#001220',
} as const;

export const background = {
  base: '#0A0A0F',
  surface: '#13131A',
  elevated: '#1C1C26',
} as const;

export const brand = {
  primary: '#00D4FF',
  secondary: '#0099CC',
} as const;

export const text = {
  primary: '#F8FAFC',
  secondary: '#94A3B8',
  muted: '#475569',
  inverse: '#0A0A0F',
} as const;

export const status = {
  success: '#22C55E',
  warning: '#F59E0B',
  error: '#EF4444',
} as const;

export const border = {
  default: '#334155',
  subtle: '#1C1C26',
  focus: '#00D4FF',
} as const;

export const buttonTokens = {
    primary: {
      background: '#00D4FF',
      text: '#0A0A0F',
    },
    secondary: {
      background: '#0099CC',
      text: '#00D4FF',
    },
    destructive: {
      background: '#EF4444',
      text: '#FFFFFF',
    },
    disabled: {
      background: '#1C1C26',
      text: '#475569',
    },
    radius: 8,
  } as const;

export const colors = {
  neutral,
  blue,
  background,
  brand,
  text,
  status,
  border,
  buttonTokens,
} as const;
