// Auto-generated by Style Dictionary — do not edit manually

export const radii = {
  none: 0,
  xs: 2,
  sm: 4,
  md: 8,
  lg: 12,
  xl: 16,
  '2xl': 20,
  '3xl': 24,
  '4xl': 32,
  full: 9999,
} as const;

export const componentRadius = {
  buttonSm: 4,
  buttonMd: 8,
  cardSm: 8,
  cardLg: 12,
  input: 8,
  modal: 16,
  avatar: 9999,
  badge: 9999,
  tab: 4,
} as const;

export const radius = {
  radii,
  component: componentRadius,
} as const;
