// Auto-generated by Style Dictionary — do not edit manually

export const space = {
  px: 2,
  '1': 4,
  '2': 8,
  '3': 12,
  '4': 16,
  '5': 20,
  '6': 24,
  '8': 32,
  '10': 40,
  '12': 48,
  '16': 64,
  '20': 48,
} as const;

export const layout = {
  screenHorizontal: 16,
  screenVertical: 24,
  cardPadding: 16,
  cardGap: 12,
  sectionGap: 32,
  listItemGap: 8,
  iconGap: 8,
  navHeight: 48,
} as const;

export const spacing = {
  space,
  layout,
} as const;
