// Auto-generated by Style Dictionary — do not edit manually

export const fontFamily = {
  displaySemiBold: 'BarlowCondensed_600SemiBold',
  displayBold: 'BarlowCondensed_700Bold',
  displayExtraBold: 'BarlowCondensed_800ExtraBold',
  bodyRegular: 'Inter_400Regular',
  bodyMedium: 'Inter_500Medium',
  bodySemiBold: 'Inter_600SemiBold',
  bodyBold: 'Inter_700Bold',
  monoRegular: 'JetBrainsMono_400Regular',
  monoMedium: 'JetBrainsMono_500Medium',
} as const;

export const fontSize = {
  '10': 10,
  '11': 11,
  '12': 12,
  '13': 13,
  '14': 14,
  '16': 16,
  '18': 18,
  '20': 20,
  '24': 24,
  '28': 28,
  '30': 30,
  '32': 32,
  '36': 36,
  '48': 48,
  '60': 60,
  '64': 64,
  '72': 72,
} as const;

export const lineHeight = {
  none: 1,
  tight: 1.1,
  snug: 1.25,
  normal: 1.5,
  relaxed: 1.625,
} as const;

export const letterSpacing = {
  tight: -0.02,
  normal: 0,
  wide: 0.05,
  wider: 0.1,
  widest: 0.15,
} as const;

export const display = {
  '2xl': {
    fontFamily: 'BarlowCondensed_700Bold',
    fontSize: 64,
    lineHeight: 64,
    letterSpacing: -1.28,
  },
  'xl': {
    fontFamily: 'BarlowCondensed_700Bold',
    fontSize: 48,
    lineHeight: 52.8,
    letterSpacing: -0.96,
  },
  lg: {
    fontFamily: 'BarlowCondensed_700Bold',
    fontSize: 36,
    lineHeight: 39.6,
    letterSpacing: -0.72,
  },
  md: {
    fontFamily: 'BarlowCondensed_600SemiBold',
    fontSize: 28,
    lineHeight: 35,
    letterSpacing: 0,
  },
  sm: {
    fontFamily: 'BarlowCondensed_600SemiBold',
    fontSize: 24,
    lineHeight: 30,
    letterSpacing: 0,
  },
} as const;

export const body = {
  'xl': {
    fontFamily: 'Inter_400Regular',
    fontSize: 20,
    lineHeight: 30,
  },
  lg: {
    fontFamily: 'Inter_400Regular',
    fontSize: 18,
    lineHeight: 27,
  },
  md: {
    fontFamily: 'Inter_400Regular',
    fontSize: 16,
    lineHeight: 24,
  },
  sm: {
    fontFamily: 'Inter_400Regular',
    fontSize: 14,
    lineHeight: 21,
  },
  xs: {
    fontFamily: 'Inter_400Regular',
    fontSize: 12,
    lineHeight: 18,
  },
} as const;

export const label = {
  lg: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 16,
    lineHeight: 20,
  },
  md: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 14,
    lineHeight: 17.5,
  },
  sm: {
    fontFamily: 'Inter_500Medium',
    fontSize: 12,
    lineHeight: 15,
  },
  caps: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 12,
    lineHeight: 15,
    letterSpacing: 1.8,
    textTransform: 'uppercase' as const,
  },
} as const;

export const mono = {
  'xl': {
    fontFamily: 'JetBrainsMono_500Medium',
    fontSize: 32,
    lineHeight: 32,
  },
  lg: {
    fontFamily: 'JetBrainsMono_500Medium',
    fontSize: 24,
    lineHeight: 24,
  },
  md: {
    fontFamily: 'JetBrainsMono_400Regular',
    fontSize: 18,
    lineHeight: 18,
  },
  sm: {
    fontFamily: 'JetBrainsMono_400Regular',
    fontSize: 14,
    lineHeight: 14,
  },
} as const;

export const typography = {
  fontFamily,
  fontSize,
  lineHeight,
  letterSpacing,
  display,
  body,
  label,
  mono,
} as const;
